baseURL = "https://AetherHJF.netlify.app/"
languageCode = "zh-cn"
title = "Aether's BLOG"
theme = "Aether"

paginate = 10000
ArchivePaginate = 10000

DisqusShortname = "divinerhjf"

enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:filename/"

[menu]
  [[menu.main]]
    name = "ğŸ—ƒï¸ å½’æ¡£"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "ğŸ± åˆ†ç±»"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "ğŸ·ï¸ æ ‡ç­¾"
    url = "/tags/"
    weight = 3



[params]
    since = 2017
    author = "Jianfeng.Hao"                           # Author's name
    avatar = "/images/me/avatar.jpeg"           # Author's avatar
    subtitle = "Okay guys class is over ...."         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    toc = true                # æ˜¯å¦å¼€å¯ç›®å½•
    autoCollapseToc = true   # Auto expand and collapse toc

    google_verification = ""

    description = "DivinerHJF's BLOG" # site description
    keywords = "BLOG, Tech, Life" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= 'æœ¬æ–‡é‡‡ç”¨<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨ 4.0 å›½é™…è®¸å¯åè®®</a>è¿›è¡Œè®¸å¯'

[params.social]
    GitHub = "https://github.com/DivinerHJF"
    #Twitter = "xxoo"
    Email   = "haojianfeng1997@gmail.com"
    Instagram = "haojianfeng1997"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    #Facebook = "xxoo"
    Telegram = "Aether_Q"
    #Dribbble = "xxoo"
    #Medium = "xxoo"

