baseURL = "https://philohao.com/"
# [en, zh-cn, fr, ...] è®¾ç½®é»˜è®¤çš„è¯­è¨€
defaultContentLanguage = "zh-cn"
# ç½‘ç«™è¯­è¨€, ä»…åœ¨è¿™é‡Œ CN å¤§å†™
languageCode = "zh-CN"
# æ˜¯å¦åŒ…æ‹¬ä¸­æ—¥éŸ©æ–‡å­—
hasCJKLanguage = true

# æ›´æ”¹ä½¿ç”¨ Hugo æ„å»ºç½‘ç«™æ—¶ä½¿ç”¨çš„é»˜è®¤ä¸»é¢˜
theme = "aether"

title = "JianFeng Hao | éƒå»ºé”‹"

[menu]
[[menu.main]]
identifier = "posts"
name = "å½’æ¡£"
post = ""
pre = "ğŸ—ƒï¸"
title = "æ‰€æœ‰æ–‡ç« "
url = "/posts/"
weight = 1
# [[menu.main]]
# identifier = ""
# # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
# pre = "ğŸ—ƒï¸"
# # ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
# name = "å¤•æ‹¾èŠ±"
# post = ""
# url = "/series/å¤•æ‹¾èŠ±/"
# # å½“ä½ å°†é¼ æ ‡æ‚¬åœåœ¨æ­¤èœå•é“¾æ¥ä¸Šæ—¶, å°†æ˜¾ç¤ºçš„æ ‡é¢˜
# title = "ç”Ÿæ´»ã€æœˆæŠ¥ç±»æ–‡ç« "
# weight = 2
[[menu.main]]
identifier = "categories"
name = "åˆ†ç±»"
post = ""
pre = "ğŸ±"
title = "åˆ†ç±»æ–‡ç« "
url = "/categories/"
weight = 2
# [[menu.main]]
# identifier = "tags"
# name = "æ ‡ç­¾"
# post = ""
# pre = "ğŸ·ï¸"
# title = "é‡‡ç‚¹ç‚¹æ˜Ÿå…‰ç»œç»“ä¸ºç½‘"
# url = "/tags/"
# weight = 4
[[menu.main]]
identifier = "series"
name = "ç³»åˆ—"
post = ""
pre = "ğŸ¡"
title = "ç³»åˆ—æ–‡ç« "
url = "/series/"
weight = 5
[[menu.main]]
identifier = ""
name = "å…³äº"
post = ""
pre = "ğŸ‘¨â€ğŸ”§"
title = "å…³äºæˆ‘ä»¥åŠæˆ‘çš„ç½‘ç«™"
url = "/pages/about/"
weight = 6

[params]
#  DoIt ä¸»é¢˜ç‰ˆæœ¬
version = "0.2.X"
# ç½‘ç«™åç§°
title = "ç¿è‹¥æ˜Ÿæ²³"
# ç½‘ç«™æè¿°
description = "Personal website of JianFeng Hao | éƒå»ºé”‹çš„ä¸ªäººç½‘ç«™"
# ç½‘ç«™å…³é”®è¯
keywords = ["blog", "Hugo", "éƒå»ºé”‹", "åšå®¢"]
#  ç½‘ç«™é»˜è®¤ä¸»é¢˜æ ·å¼ ("light", "dark", "black", "auto")
defaultTheme = "auto"
# å…¬å…± git ä»“åº“è·¯å¾„, ä»…åœ¨ enableGitInfo è®¾ä¸º true æ—¶æœ‰æ•ˆ
gitRepo = ""
#  å“ªç§å“ˆå¸Œå‡½æ•°ç”¨æ¥ SRI, ä¸ºç©ºæ—¶è¡¨ç¤ºä¸ä½¿ç”¨ SRI
# ("sha256", "sha384", "sha512", "md5")
fingerprint = ""
#  æ—¥æœŸæ ¼å¼
dateFormat = "2006-01-02"
# ç½‘ç«™å›¾ç‰‡, ç”¨äº Open Graph å’Œ Twitter Cards
images = ["/images/me/favicon.svg"]
#  å¼€å¯PWAæ”¯æŒ
enablePWA = true
#  åº”ç”¨å›¾æ ‡é…ç½®
[params.app]
# å½“æ·»åŠ åˆ° iOS ä¸»å±å¹•æˆ–è€… Android å¯åŠ¨å™¨æ—¶çš„æ ‡é¢˜, è¦†ç›–é»˜è®¤æ ‡é¢˜
title = "Aether"
# æ˜¯å¦éšè—ç½‘ç«™å›¾æ ‡èµ„æºé“¾æ¥
noFavicon = false
# æ›´ç°ä»£çš„ SVG ç½‘ç«™å›¾æ ‡, å¯æ›¿ä»£æ—§çš„ .png å’Œ .ico æ–‡ä»¶
svgFavicon = "/images/me/favicon.svg"
# Safari å›¾æ ‡é¢œè‰²
iconColor = "#5bbad5"
# Windows v8-10ç£è´´é¢œè‰²
tileColor = "#da532c"

#  æœç´¢é…ç½®
[params.search]
enable = true
# æœç´¢å¼•æ“çš„ç±»å‹ ("lunr", "algolia", "fuse")
type = "fuse"
# æ–‡ç« å†…å®¹æœ€é•¿ç´¢å¼•é•¿åº¦
contentLength = 1000000
# æœç´¢æ¡†çš„å ä½æç¤ºè¯­
placeholder = ""
#  æœ€å¤§ç»“æœæ•°ç›®
maxResultLength = 10
#  ç»“æœå†…å®¹ç‰‡æ®µé•¿åº¦
snippetLength = 50
#  æœç´¢ç»“æœä¸­é«˜äº®éƒ¨åˆ†çš„ HTML æ ‡ç­¾
highlightTag = "em"
#  æ˜¯å¦åœ¨æœç´¢ç´¢å¼•ä¸­ä½¿ç”¨åŸºäº baseURL çš„ç»å¯¹è·¯å¾„
absoluteURL = false
[params.search.algolia]
appID = ""
index = ""
searchKey = ""
[params.search.fuse]
#  https://fusejs.io/api/options.html
distance = 100
findAllMatches = false
ignoreFieldNorm = false
ignoreLocation = false
isCaseSensitive = false
location = 0
minMatchCharLength = 2
threshold = 0.3
useExtendedSearch = false

# é¡µé¢å¤´éƒ¨å¯¼èˆªæ é…ç½®
[params.header]
# æ¡Œé¢ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
desktopMode = "auto"
# ç§»åŠ¨ç«¯å¯¼èˆªæ æ¨¡å¼ ("fixed", "normal", "auto")
mobileMode = "auto"
#  ä¸»é¢˜åˆ‡æ¢æ¨¡å¼
# ä¸»é¢˜åˆ‡æ¢æ¨¡å¼ ("switch", "select")
themeChangeMode = "select"
#  é¡µé¢å¤´éƒ¨å¯¼èˆªæ æ ‡é¢˜é…ç½®
[params.header.title]
# LOGO çš„ URL
logo = "/images/me/logo.svg"
# æ ‡é¢˜åç§°
name = "æ˜Ÿæ²³ä¸€æ–¹"
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹å‰æ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
pre = ""
# ä½ å¯ä»¥åœ¨åç§° (å…è®¸ HTML æ ¼å¼) ä¹‹åæ·»åŠ å…¶ä»–ä¿¡æ¯, ä¾‹å¦‚å›¾æ ‡
post = ""
#  æ˜¯å¦ä¸ºæ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = false

# é¡µé¢åº•éƒ¨ä¿¡æ¯é…ç½®
[params.footer]
enable = true
#  è‡ªå®šä¹‰å†…å®¹ (æ”¯æŒ HTML æ ¼å¼)
custom = '<a href="/pages/now/" target="_blank" rel="noreferrer">æ­¤åˆ»</a> Â· <a href="/pages/footprint/" target="_blank">è¶³è¿¹</a> Â· <a href="/pages/mentalfood/" target="_blank">é˜…è§ˆ</a> Â· <a href="/pages/album/" target="_blank">å›å¿†</a> <hr width="20px" color="#D3D3D3">'
#  æ˜¯å¦æ˜¾ç¤º Hugo å’Œä¸»é¢˜ä¿¡æ¯
hugo = false
#  æ˜¯å¦æ˜¾ç¤ºç‰ˆæƒä¿¡æ¯
copyright = true
#  æ˜¯å¦æ˜¾ç¤ºä½œè€…
author = true
# ç½‘ç«™åˆ›ç«‹å¹´ä»½
since = 2017
# ICP å¤‡æ¡ˆä¿¡æ¯, ä»…åœ¨ä¸­å›½ä½¿ç”¨ (æ”¯æŒ HTML æ ¼å¼)
icp = ""
# è®¸å¯åè®®ä¿¡æ¯ (æ”¯æŒ HTML æ ¼å¼)
# license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

#  Section (æ‰€æœ‰æ–‡ç« ) é¡µé¢é…ç½®
[params.section]
# section é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 10000
# æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 100
#  æœ€è¿‘æ›´æ–°æ–‡ç« è®¾ç½®
[params.section.recentlyUpdated]
days = 30
enable = true
maxCount = 5
rss = true

#  List (ç›®å½•æˆ–æ ‡ç­¾) é¡µé¢é…ç½®
[params.list]
# list é¡µé¢æ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 1000
# æ—¥æœŸæ ¼å¼ (æœˆå’Œæ—¥)
dateFormat = "01-02"
# RSS æ–‡ç« æ•°ç›®
rss = 100

# ä¸»é¡µé…ç½®
[params.home]
#  RSS æ–‡ç« æ•°ç›®
rss = 100
# ä¸»é¡µä¸ªäººä¿¡æ¯
[params.home.profile]
enable = true
# Gravatar é‚®ç®±, ç”¨äºä¼˜å…ˆåœ¨ä¸»é¡µæ˜¾ç¤ºçš„å¤´åƒ
gravatarEmail = ""
# ä¸»é¡µæ˜¾ç¤ºå¤´åƒçš„ URL
# å°†ä½ çš„å¤´åƒæ–‡ä»¶æ”¾ç½®äº static æˆ–è€… assets ç›®å½•ä¸‹
# æ–‡ä»¶è·¯å¾„æ˜¯ç›¸å¯¹äº static æˆ–è€… assets ç›®å½•çš„
avatarURL = "/images/me/avatar.svg"
#  ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™æ ‡é¢˜ (æ”¯æŒ HTML æ ¼å¼)
title = "Aether"
# ä¸»é¡µæ˜¾ç¤ºçš„ç½‘ç«™å‰¯æ ‡é¢˜
subtitle = "Okay guys class is over ...."
# æ˜¯å¦ä¸ºå‰¯æ ‡é¢˜æ˜¾ç¤ºæ‰“å­—æœºåŠ¨ç”»
typeit = false
# æ˜¯å¦æ˜¾ç¤ºç¤¾äº¤è´¦å·
social = true
#  å…è´£å£°æ˜ (æ”¯æŒ HTML æ ¼å¼)
disclaimer = ""
# ä¸»é¡µæ–‡ç« åˆ—è¡¨
[params.home.posts]
enable = false
# ä¸»é¡µæ¯é¡µæ˜¾ç¤ºæ–‡ç« æ•°é‡
paginate = 6
#  è¢« params.page ä¸­çš„ hiddenFromHomePage æ›¿ä»£
# å½“ä½ æ²¡æœ‰åœ¨æ–‡ç« å‰ç½®å‚æ•°ä¸­è®¾ç½® "hiddenFromHomePage" æ—¶çš„é»˜è®¤è¡Œä¸º
defaultHiddenFromHomePage = false

# ä½œè€…çš„ç¤¾äº¤ä¿¡æ¯è®¾ç½®
# æ‰€æœ‰æ”¯æŒçš„ç¤¾äº¤é“¾æ¥çš„é»˜è®¤æ•°æ®ä½äº themes/DoIt/assets/data/social.yaml. ä½ å¯ä»¥å‚è€ƒå®ƒæ¥é…ç½®ä½ çš„ç¤¾äº¤é“¾æ¥.
[params.social]
Angellist = ""
Bandcamp = ""
Behance = ""
Bilibili = ""
Bitbucket = ""
BuyMeACoffee = ""
Codepen = ""
Deviantart = ""
Devto = ""
Douban = ""
Dribbble = ""
Email = "haojianfeng1997@gmail.com"
Facebook = ""
Fivehundredpx = ""
Flickr = ""
Foursquare = ""
FreeCodeCamp = ""
GitHub = "DivinerHJF"
Gitea = ""
Gitlab = ""
Goodreads = ""
Googlescholar = ""
Hackernews = ""
Instagram = ""
Jsfiddle = ""
Keybase = ""
Kickstarter = ""
Ko-Fi = ""
Lastfm = ""
Liberapay = ""
Linkedin = ""
Linktree = ""
Mastodon = "@PhiloHao"
Matrix = ""
Medium = ""
Mix = ""
ORCID = ""
Odnoklassniki = ""
Patreon = ""
Paypal = ""
Pinterest = ""
QQGroup = ""
Quora = ""
RSS = true
Reddit = ""
Researchgate = ""
Skype = ""
Slidershare = ""
Snapchat = ""
Soundcloud = ""
Spotify = ""
Stackoverflow = ""
Steam = ""
Strava = ""
Telegram = "Aether_Q"
Thingiverse = ""
Tumblr = ""
Twitch = ""
Twitter = ""
VK = ""
Vine = ""
Weibo = ""
Whatsapp = ""
Wordpress = ""
XMPP = ""
Xing = ""
Youtubechannel = ""
Youtubecustom = ""
Youtubelegacy = ""
Zhihu = ""

#  æ–‡ç« é¡µé¢é…ç½®
[params.page]
#  æ˜¯å¦åœ¨ä¸»é¡µéšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromHomePage = false
#  æ˜¯å¦åœ¨æœç´¢ç»“æœä¸­éšè—ä¸€ç¯‡æ–‡ç« 
hiddenFromSearch = false
#  æ˜¯å¦ä½¿ç”¨ twemoji
twemoji = false
# æ˜¯å¦ä½¿ç”¨ lightgallery
lightgallery = false
#  æ˜¯å¦ä½¿ç”¨ ruby æ‰©å±•è¯­æ³•
ruby = true
#  æ˜¯å¦ä½¿ç”¨ fraction æ‰©å±•è¯­æ³•
fraction = true
#  æ˜¯å¦ä½¿ç”¨ fontawesome æ‰©å±•è¯­æ³•
fontawesome = true
# æ˜¯å¦åœ¨æ–‡ç« é¡µé¢æ˜¾ç¤ºåŸå§‹ Markdown æ–‡æ¡£é“¾æ¥
linkToMarkdown = true
#  æ˜¯å¦åœ¨ RSS ä¸­æ˜¾ç¤ºå…¨æ–‡å†…å®¹
rssFullText = true
#  é¡µé¢æ ·å¼ ("normal", "wide")
pageStyle = "normal"
#  è¿‡æ—¶æ–‡ç« æç¤º
[params.page.outdatedArticleReminder]
enable = true
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº 90 å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºæé†’
reminder = 90
# å¦‚æœæ–‡ç« æœ€åæ›´æ–°äº 180 å¤©ä¹‹å‰ï¼Œæ˜¾ç¤ºè­¦å‘Š
warning = 180
#  ç›®å½•é…ç½®
[params.page.toc]
# æ˜¯å¦ä½¿ç”¨ç›®å½•
enable = true
#  æ˜¯å¦ä¿æŒä½¿ç”¨æ–‡ç« å‰é¢çš„é™æ€ç›®å½•
keepStatic = false
# æ˜¯å¦ä½¿ä¾§è¾¹ç›®å½•è‡ªåŠ¨æŠ˜å å±•å¼€
auto = false
#  ä»£ç é…ç½®
[params.page.code]
# æ˜¯å¦æ˜¾ç¤ºä»£ç å—çš„å¤åˆ¶æŒ‰é’®
copy = true
# é»˜è®¤å±•å¼€æ˜¾ç¤ºçš„ä»£ç è¡Œæ•°
maxShownLines = 15
#  KaTeX æ•°å­¦å…¬å¼
[params.page.math]
enable = true
# é»˜è®¤å—å®šç•Œç¬¦æ˜¯ $$ ... $$ å’Œ \\[ ... \\]
blockLeftDelimiter = ""
blockRightDelimiter = ""
# é»˜è®¤è¡Œå†…å®šç•Œç¬¦æ˜¯ $ ... $ å’Œ \\( ... \\)
inlineLeftDelimiter = ""
inlineRightDelimiter = ""
# KaTeX æ’ä»¶ copy_tex
copyTex = true
# KaTeX æ’ä»¶ mhchem
mhchem = true
#  Mapbox GL JS é…ç½®
[params.page.mapbox]
# Mapbox GL JS çš„ access token
accessToken = ""
# æµ…è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
lightStyle = "mapbox://styles/mapbox/light-v9"
# æ·±è‰²ä¸»é¢˜çš„åœ°å›¾æ ·å¼
darkStyle = "mapbox://styles/mapbox/dark-v9"
# æ˜¯å¦æ·»åŠ  NavigationControl
navigation = true
# æ˜¯å¦æ·»åŠ  GeolocateControl
geolocate = true
# æ˜¯å¦æ·»åŠ  ScaleControl
scale = true
# æ˜¯å¦æ·»åŠ  FullscreenControl
fullscreen = true
#  æ–‡ç« é¡µé¢çš„åˆ†äº«ä¿¡æ¯è®¾ç½®
[params.page.share]
Baidu = false
Blogger = false
Buffer = false
Digg = false
Evernote = true
Facebook = false
Flipboard = false
HackerNews = false
Instapaper = false
Line = false
Linkedin = false
Mix = false
Myspace = false
Odnoklassniki = false
Pinterest = false
Pocket = true
Reddit = true
Renren = false
Skype = false
Stumbleupon = false
Trello = false
Tumblr = false
Twitter = true
VK = false
Weibo = true
Whatsapp = false
Xing = false
enable = true
#  è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment]
enable = true
# Disqus è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.disqus]
# 
enable = false
# Disqus çš„ shortname, ç”¨æ¥åœ¨æ–‡ç« ä¸­å¯ç”¨ Disqus è¯„è®ºç³»ç»Ÿ
shortname = ""
# Gitalk è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.gitalk]
# 
clientId = ""
clientSecret = ""
enable = false
owner = ""
repo = ""
# Valine è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.valine]
appId = ""
appKey = ""
avatar = "mp"
enable = false
enableQQ = false
highlight = true
lang = ""
meta = ""
pageSize = 10
placeholder = ""
recordIP = true
serverURLs = ""
visitor = true
#  emoji æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤æ˜¯ "google.yml"
# ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
# ä½äº "themes/DoIt/assets/data/emoji/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
# "assets/data/emoji/"
emoji = ""
# Waline è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.waline]
# 
commentCount = true
emoji = ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
enable = true
highlight = true
login = 'enable'
mathTagSupport = true
meta = ['nick', 'mail', 'link']
pageSize = 10
requiredMeta = []
serverURL = "https://blog-commit-api.vercel.app/"
uploadImage = true
visitor = true
wordLimit = 0
# Facebook è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.facebook]
appId = ""
enable = false
languageCode = "zh_CN"
numPosts = 10
width = "100%"
#  Telegram Comments è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.telegram]
color = ""
colorful = true
dark = false
dislikes = false
enable = false
height = ""
limit = 5
outlined = false
siteID = ""
#  Commento è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.commento]
enable = false
#  Utterances è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.utterances]
enable = false
# owner/repo
darkTheme = "github-dark"
issueTerm = "pathname"
label = ""
lightTheme = "github-light"
repo = ""
#  Twikoo è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.twikoo]
commentCount = true
enable = false
envId = ""
path = ""
region = ""
visitor = true
#  Vssue è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.vssue]
clientId = "" 
clientSecret = "" 
enable = false 
owner = "" 
platform = "" # ("bitbucket", "gitea", "gitee", "github", "gitlab")
repo = "" 
#  Remark42 è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.remark42]
enable = false
host = ""
max_shown_comments = 15
show_email_subscription = true
simple_view = false
site_id = ""
#  giscus è¯„è®ºç³»ç»Ÿè®¾ç½®
[params.page.comment.giscus]
enable = false
# owner/repo
darkTheme = "dark"
dataCategory = ""
dataCategoryId = ""
dataEmitMetadata = "0"
dataMapping = "pathname"
dataReactionsEnabled = "1"
dataRepo = ""
dataRepoId = ""
lightTheme = "light"
#  ç¬¬ä¸‰æ–¹åº“é…ç½®
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# ä½äº "assets/"
# æˆ–è€…
# someCSS = "https://cdn.example.com/some.css"
[params.page.library.js]
# someJavascript = "some.js"
# ä½äº "assets/"
# æˆ–è€…
# someJavascript = "https://cdn.example.com/some.js"
#  é¡µé¢ SEO é…ç½®
[params.page.seo]
# å›¾ç‰‡ URL
images = []
# å‡ºç‰ˆè€…ä¿¡æ¯
[params.page.seo.publisher]
logoUrl = ""
name = ""

#  èµèµé…ç½®
[params.sponsor]
bio = "å¦‚æœä½ è§‰å¾—è¿™ç¯‡æ–‡ç« å¯¹ä½ æœ‰æ‰€å¸®åŠ©ï¼Œæ¬¢è¿èµèµ~" 
custom = "" # è‡ªå®šä¹‰ HTML 
enable = false 
link = "https://www.buymeacoffee.com" # ä½ çš„èµèµé¡µé¢çš„åœ°å€

#  TypeIt é…ç½®
[params.typeit]
# æ¯ä¸€æ­¥çš„æ‰“å­—é€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
speed = 100
# å…‰æ ‡çš„é—ªçƒé€Ÿåº¦ (å•ä½æ˜¯æ¯«ç§’)
cursorSpeed = 1000
# å…‰æ ‡çš„å­—ç¬¦ (æ”¯æŒ HTML æ ¼å¼)
cursorChar = "|"
# æ‰“å­—ç»“æŸä¹‹åå…‰æ ‡çš„æŒç»­æ—¶é—´ (å•ä½æ˜¯æ¯«ç§’, "-1" ä»£è¡¨æ— é™å¤§)
duration = -1

# ç½‘ç«™éªŒè¯ä»£ç , ç”¨äº Google/Bing/Yandex/Pinterest/Baidu
[params.verification]
baidu = "" 
bing = "" 
google = "" 
pinterest = "" 
so = "" # 360 search
sogou = "" 
yandex = "" 

#  ç½‘ç«™ SEO é…ç½®
[params.seo]
# å›¾ç‰‡ URL
image = "https://blog-1255524710.cos.ap-beijing.myqcloud.com/master/2022031021531069866.svg"
# ç¼©ç•¥å›¾ URL
thumbnailUrl = "https://blog-1255524710.cos.ap-beijing.myqcloud.com/master/2022031021545432128.svg"

#  ç½‘ç«™åˆ†æé…ç½®
[params.analytics]
enable = true
# Google Analytics
[params.analytics.google]
id = ""
# æ˜¯å¦åŒ¿ååŒ–ç”¨æˆ· IP
anonymizeIP = true
# Fathom Analytics
[params.analytics.fathom]
id = ""
# è‡ªè¡Œæ‰˜ç®¡è¿½è¸ªå™¨æ—¶çš„ä¸»æœºè·¯å¾„
server = ""
#  Baidu Analytics
[params.analytics.baidu]
id = ""
#  Umami Analytics
[params.analytics.umami]
data_domains = ""
data_website_id = ""
src = ""
#  Plausible Analytics
[params.analytics.plausible]
data_domain = ""
src = ""

#  Cookie è®¸å¯é…ç½®
[params.cookieconsent]
enable = true
# ç”¨äº Cookie è®¸å¯æ¨ªå¹…çš„æ–‡æœ¬å­—ç¬¦ä¸²
[params.cookieconsent.content]
dismiss = ""
link = ""
message = ""

#  ç¬¬ä¸‰æ–¹åº“æ–‡ä»¶çš„ CDN è®¾ç½®
[params.cdn]
# CDN æ•°æ®æ–‡ä»¶åç§°, é»˜è®¤ä¸å¯ç”¨
# ("jsdelivr.yml")
# ä½äº "themes/DoIt/assets/data/cdn/" ç›®å½•
# å¯ä»¥åœ¨ä½ çš„é¡¹ç›®ä¸‹ç›¸åŒè·¯å¾„å­˜æ”¾ä½ è‡ªå·±çš„æ•°æ®æ–‡ä»¶:
# "assets/data/cdn/"
data = ""

#  å…¼å®¹æ€§è®¾ç½®
[params.compatibility]
# æ˜¯å¦ä½¿ç”¨ Polyfill.io æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
polyfill = false
# æ˜¯å¦ä½¿ç”¨ object-fit-images æ¥å…¼å®¹æ—§å¼æµè§ˆå™¨
objectFit = false

# Hugo è§£ææ–‡æ¡£çš„é…ç½®
[markup]
# è¯­æ³•é«˜äº®è®¾ç½®
[markup.highlight]
codeFences = true
guessSyntax = true
lineNos = true
lineNumbersInTable = true
# style = "pygments"
# false æ˜¯å¿…è¦çš„è®¾ç½®
# (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false
# Goldmark æ˜¯ Hugo 0.60 ä»¥æ¥çš„é»˜è®¤ Markdown è§£æåº“
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true
[markup.goldmark.renderer]
# æ˜¯å¦åœ¨æ–‡æ¡£ä¸­ç›´æ¥ä½¿ç”¨ HTML æ ‡ç­¾
unsafe = true
# ç›®å½•è®¾ç½®
[markup.tableOfContents]
endLevel = 6
startLevel = 2

# ä½œè€…é…ç½®
[author]
avatar = "https://www.aetherhjf.com/images/me/logo.svg"
email = "haojianfeng1997@gmail.com"
gravatarEmail = ""
link = "https://aetherhjf.com/"
name = "Jianfeng.Hao"

# ç½‘ç«™åœ°å›¾é…ç½®
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

# Permalinks é…ç½®
[Permalinks]
# posts = ":year/:month/:filename"
posts = ":year/:month/:filename"

# éšç§ä¿¡æ¯é…ç½®
[privacy]
#  Google Analytics ç›¸å…³éšç§ (è¢« params.analytics.google æ›¿ä»£)
[privacy.googleAnalytics]
# ...
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[mediaTypes]
[mediaTypes."text/plain"]
suffixes = ["md"]

# ç”¨äºè¾“å‡º Markdown æ ¼å¼æ–‡æ¡£çš„è®¾ç½®
[outputFormats.MarkDown]
isHTML = false
isPlainText = true
mediaType = "text/plain"

# ç”¨äº Hugo è¾“å‡ºæ–‡æ¡£çš„è®¾ç½®
[outputs]
# 
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "MarkDown"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
taxonomyTerm = ["HTML"]

# ç”¨äºåˆ†ç±»çš„è®¾ç½®
[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"
